grafana:
  enabled: true
  adminPassword: admin123
  service:
    type: LoadBalancer
  defaultDashboardsEnabled: true

prometheus:
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

