apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.api.name }}
  ports:
  - port: 80
    targetPort: {{ .Values.api.port }}
