apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.registry }}/service-api:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.api.port }}
        envFrom:
        - configMapRef:
            name: recruitment-config
        - secretRef:
            name: recruitment-secrets
        resources:
{{ toYaml .Values.api.resources | indent 10 }}
