apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ui.name }}
    spec:
      containers:
      - name: ui
        image: "{{ .Values.image.registry }}/service-ui:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.ui.port }}
        resources:
{{ toYaml .Values.ui.resources | indent 10 }}
